---
- hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
      notify: Restart Apache

    - name: Create custom index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted